  docker_build_and_run:
    runs-on: ubuntu-latest
    needs: [build_on_linux, build_on_windows]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t logger .
        
      - name: Create logs directory
        run: mkdir -p logs
        
      - name: Run container with input
        run: |
          # Запускаем контейнер с передачей входных данных
          echo -e "1\n-5\n6" | docker run -i -v "$(pwd)/logs/:/home/logs/" --name logger-container logger
          sleep 1  # Даем время на запись логов
          
      - name: Debug container output
        run: |
          echo "Container logs:"
          docker logs logger-container || true
          echo "Contents of logs directory:"
          ls -la logs/
          echo "Trying to read log file:"
          cat logs/log.txt || echo "Log file not found"
          
      - name: Verify logs
        run: |
          if [ ! -f logs/log.txt ]; then
            echo "Error: Log file was not created!"
            echo "Possible reasons:"
            echo "1. LOG_PATH in container is not set correctly"
            echo "2. Application doesn't have permissions to write to /home/logs/"
            echo "3. Application is not actually writing to the log file"
            exit 1
          fi
          echo "Log file content:"
          cat logs/log.txt
          
      - name: Cleanup container
        if: always()
        run: |
          docker stop logger-container || true
          docker rm logger-container || true
          
      - name: Upload logs artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: logs/log.txt