name: CI workflow

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - cpp_comp: g++
            c_comp: gcc
          - cpp_comp: clang++
            c_comp: clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: cmake -H. -B_build -DCMAKE_CXX_COMPILER=${{matrix.cpp_comp}} -DCMAKE_C_COMPILER=${{matrix.c_comp}}
      
      - name: Build
        run: cmake --build _build
      
      - name: Test programs
        run: |
          echo "1 -5 6" | _build/solver_application/solver_app
          _build/hello_world_application/hello

  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: cmake . -B_build
      
      - name: Build
        run: cmake --build _build
      
      - name: Test programs
        run: |
          echo "1 -5 6" | _build\solver_application\Debug\solver_app
          _build\hello_world_application\Debug\hello

  docker_build_and_run:
    runs-on: ubuntu-latest
    needs: [build_on_linux, build_on_windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t logger .
        
      - name: Create logs directory
        run: mkdir -p logs
        
      - name: Run container with test input
        run: |
          echo -e "1\n-5\n6" | docker run -i -v "$(pwd)/logs/:/home/logs/" --name logger-container logger
          sleep 1
          
      - name: Verify logs
        run: |
          if [ -f logs/log.txt ]; then
            echo "Log file content:"
            cat logs/log.txt
          else
            echo "Error: Log file not found!"
            docker logs logger-container || true
            exit 1
          fi
          
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: logs/log.txt