name: CI workflow

on: [push, pull_request]

jobs:
  docker_build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t logger .
        
      - name: Test with valid input
        run: |
          echo "Testing equation solver:"
          output=$(echo "1 -5 6" | docker run -i --rm logger)
          echo "$output"
          
          # Проверяем корректность решения
          if [[ "$output" != *"nan"* && "$output" == *"x1 ="* && "$output" == *"x2 ="* ]]; then
            echo "Valid solution found"
          else
            echo "ERROR: Invalid solution detected!"
            echo "Debug info:"
            echo "1. Checking input parsing..."
            echo "1 2 3" | docker run -i --rm logger
            echo "2. Checking zero discriminant..."
            echo "1 2 1" | docker run -i --rm logger
            exit 1
          fi
          
      - name: Save successful output
        if: success()
        run: |
          mkdir -p logs
          echo "1 -5 6" | docker run -i --rm logger > logs/solution.txt
          echo "Stored solution:"
          cat logs/solution.txt
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: solver-results
          path: logs/solution.txt